### ISSUE TITLE
split data file is not working with its given paths

### ISSUE THREAD

**Issue by romaanmirza** [theidentity/Unets#3]
split data file is producing error of paths...
i am using os windows 10 and python 3.6 and all dependencies which required for this code. but paths are not working and error is path related

error
"E:\BRL\liver\Unets-master\python programs\Scripts\python.exe" E:/BRL/liver/Unets-master/split_data.py
138
Traceback (most recent call last):
  File "E:/BRL/liver/Unets-master/split_data.py", line 60, in <module>
    copy_sets(train,test,base_path= base_path)
  File "E:/BRL/liver/Unets-master/split_data.py", line 37, in copy_sets
    copy_images(img_in_paths,img_out_paths)
  File "E:/BRL/liver/Unets-master/split_data.py", line 31, in copy_images
    shutil.copyfile(src,dst)
  File "C:\Users\VLSI_\AppData\Local\Programs\Python\Python36\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 22] Invalid argument: 'E:/BRL/liver/Unets-master/data/foldA/E:/BRL/liver/Unets-master/data/foldA/train/images/input/images_mtgm\\MCUCXR_0016_0.png'

Process finished with exit code 1

**Comment by theidentity** [comment]
Same as issue #2 
Replacing with backward slashes should do the trick.

**Comment by romaanmirza** [comment]
thanks
